baseURL = "https://fibra.click"
languageCode = "it-IT"
title = "FibraClick Wiki"

theme = "fibraclick"

removePathAccents = true

[params]
  homeTitle = "FibraClick Wiki, risposte sulla fibra ottica"
  description = "Dubbi sulla fibra ottica, copertura o intervento pubblico? FibraClick Wiki è lo spazio dedicato dove trovare risposte precise e curate."
  analytics = "UA-65084561-3"
  ads = false

[permalinks]
  posts = "/:slug"
  categories = "/c/:slug"

[taxonomies]
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingIDType = "blackfriday"

[author]
  email = "info@fibra.click"
